repository: lerss/zyqq-site
domain: lerss.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://lerss.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /zyqq-site           # place folder name if the site is served in a subfolder

plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

theme: jekyll-theme-midnight
